export const level3MetingRooms = [
  {
    id: "l3-1",
    name: "Randwick",
    desc: "Meeting room capacity: 10",
    level: 3,
  },
  {
    id: "l3-2",
    name: "Toilet",
    desc: "flush after use",
    level: 3,
  },
  {
    id: "l3-3",
    name: "VIC-HUB-L3E-01",
    desc: "Showcase your work",
    level: 3,
  },
  {
    id: "l3-4",
    name: "VIC-HUB-L3E-02",
    desc: "Showcase your work",
    level: 3,
  },
  {
    id: "l3-5",
    name: "VIC-HUB-L3E-03",
    desc: "Showcase your work",
    level: 3,
  },
  {
    id: "l3-6",
    name: "VIC-HUB-L3E-04",
    desc: "Showcase your work",
    level: 3,
  },
  {
    id: "l3-7",
    name: "VIC-HUB-L3E-05",
    desc: "Showcase your work",
    level: 3,
  },
  {
    id: "l3-8",
    name: "Kembla | Grange",
    desc: "Colab",
    level: 3,
  },
  {
    id: "l3-9",
    name: "Wagga Wagga",
    desc: "Meeting room capacity: 4",
    level: 3,
  },
  {
    id: "l3-10",
    name: "Orange",
    desc: "Meeting room capacity: 4",
    level: 3,
  },
  {
    id: "l3-11",
    name: "Forbes",
    desc: "Colab",
    level: 3,
  },
  {
    id: "l3-12",
    name: "Penrith",
    desc: "Meeting room capacity: 8",
    level: 3,
  },
  {
    id: "l3-13",
    name: "Griffith",
    desc: "Meeting room capacity: 6",
    level: 3,
  },
  {
    id: "l3-14",
    name: "Alexandria",
    desc: "Meeting room capacity: 10",
    level: 4,
  },
];
